exp_tasks_dir: &tasks_dir ./exp_tasks_dir
exp_tldr_dir: ./exp_tasks_dir/exp_tldr_dir
exp_nl2bash_dir: ./exp_tasks_dir/exp_nl2bash_dir
exp_posts_dir: ./exp_tasks_dir/exp_posts_dir
so_dir: /exp_tasks_dir/exp_posts_dir/so
superuser_dir: /exp_tasks_dir/exp_posts_dir/superuser
askubuntu_dir: /exp_tasks_dir/exp_posts_dir/askubuntu
unixlinux_dir: /exp_tasks_dir/exp_posts_dir/unixlinux
exp_models_dir: &exp_models_dir ./exp_models_dir
exp_cate_dir: *exp_models_dir
category_dir: ./exp_models_dir/categories.txt
exp_pattern_dir: *exp_models_dir
exp_graph_dir: *exp_models_dir
online: ./online
offline: ./offline
exp_manual_dir: *exp_models_dir
exp_evaluation_dir: ./exp_evaluation_dir
exp_res_dir: ./exp_res_dir
